#!/bin/bash

echo 'Loading CMAKE'
module load cmake/3.18.3

echo 'Loading Intel compilers'
module load intel/2020.2.254

echo 'Loading Intel MPI'
module load intelmpi/2020.2.254

echo 'Loading Anaconda/python'
module load python/3.8