#!/bin/bash

# USAGE: ./KurtAssist_conda <custom-conda-env-name (optional)>
# custom conda environment name is optional(DEFAULT=DFTBplus-env)

# Detect if any change to conda environment name invoked
if [ -z "$1" ]; then
    CONDA_ENV_NAME='DFTBplus-env'
    echo Using DEFAULT environment name: \" $CONDA_ENV_NAME \"
else
    CONDA_ENV_NAME=$1
    echo Using CUSTOM environment name: \" $CONDA_ENV_NAME \"
fi

# Edit conda environment yml template
SEARCH_TAG='env_template'
sed -i 's/$SEARCH_TAG/$CONDA_ENV_NAME/' KurtAssist_envTemplate.yml

# Run conda env creator



# Create conda package from yaml
# Download basic
# conda create 0c

https://github.com/kimrojas/Utility-Collection/tree/main/dftbplus/KurtAssist

svn checkout https://github.com/kimrojas/Utility-Collection/trunk/dftbplus/KurtAssist

svn export https://github.com/kimrojas/Utility-Collection/trunk/dftbplus/KurtAssist