#!/bin/bash

# Recipe needs to run in the following order:
# 1. ./run_local_intel_mpi config
# 2. ./run_local_intel_mpi build
# 3. ./run_local_intel_mpi test
# This is ust configures, builds and test the build



INP=$1
suffix='intelmpi'
option='FC=mpiifort CC=mpiicc'
builddir="${suffix}_build"
cmake_opt="-DCMAKE_INSTALL_PREFIX=${builddir}/bin -DWITH_MPI=TRUE -DWITH_OMP=FALSE -DTEST_MPI_PROCS=4"
srcdir="./"


if [ $INP == 'config' ]
then
    rm -rf $builddir
    mkdir $builddir
    command="$option cmake $cmake_opt -B $builddir $srcdir | tee ./$builddir/config_out_$suffix"
    eval $command
elif [ $INP == 'build' ]
then
    command="cmake --build $builddir -- -j  | tee ./$builddir/build_out_$suffix"
    eval $command
elif [ $INP == 'test' ]
then
    cd $builddir
    command="ctest -j4 | tee ./$builddir/test_out_$suffix"
    eval $command
    cd ..
else
    echo "Wrong input. Choose 'config', 'build' or 'test'"
fi